### ISSUE TITLE
TST 0.0.2 does not work in PM 28 in Ubuntu

### ISSUE THREAD

**Issue by graciecat** [oinkin/treestyletab#10]
TST 0.0.2 installs in PM 28 in Ubuntu, but I get no vertical tabs at all. Tested this in clean, new profile.

- Pale Moon 28.0.0a2 (64-bit) (2018-05-26)
- Ubuntu 14.04.5
- Tree Style Tabs for Pale Moon 0.0.2

**Comment by JustOff** [comment]
I'm afraid this repo is abandoned, since even trivial fixes prepared as PRs are ignored since Mar 2017. I think someone interested in TST for Pale Moon needs to make another fork.
