### ISSUE TITLE
Bookmark All Tabs is broken when using TST in PM 28.0.1

### ISSUE THREAD

**Issue by 291ce4321ac** [oinkin/treestyletab#12]
When using TST 0.0.4 in PM 28.0.1 (64b), selecting "Bookmark All Tabs" from the right-click menu will open a blank dialog box (normally it has a text field and a dropdown menu) with OK/Cancel buttons.  Clicking OK on the empty dialog does not succeed in creating a new set of bookmarks.  

This issue is present when TST is the only active extension.
This issue was not present in 27.7.1, though I don't know if it was in 28.0.0.

![screenshot at 2018-09-01 02 50 13](https://user-images.githubusercontent.com/42886494/44943824-4f2d4f00-ad92-11e8-86b7-9697dd28f974.png)

**Comment by DarkSteve** [comment]
I'm having a similar issue, except it's with creating bookmark folders and moving existing folders around. I can still create and delete individual bookmarks links, but not folders. I'm running PM 28.0.1 on Win10 x64.

When I right-click to create a folder, the pop-up dialog is blank. [Here's a screenshot](https://i.imgur.com/mPvWSeI.png).
