### ISSUE TITLE
pale moon 29 compatibility

### ISSUE THREAD

**Issue by sadpandaleafy** [oinkin/treestyletab#18]
any plans to add v29 compatibility? it's available in the unstable channel and will be pushed to stable soonTM, probably sometime before two years.

right now all tabs just break in 29 and only works with 1 tab browsing

**Comment by oinkin** [comment]
Thank you for the heads up. I plan to support 29 if I can.

**Comment by dawidi** [comment]
I upgraded to v29 just now, and indeed, it breaks this addon and I had to disable it to have any tabs at all. Horizontal tabs look *so* retro when you've had vertical tabs for years...
Is this simply a case of the addon not declaring itself compatible with PM > 28.x, or did something change in the browser that requires more work?

**Comment by zgwerby** [comment]
+1.
Has broken. Totally.

**Comment by zgwerby** [comment]
> Is this simply a case of the addon not declaring itself compatible with PM > 28.x, or did something change in the browser that requires more work?
Nope. I did it yet. Draw broken

**Comment by markd89** [comment]
bump for encouragement - 0.29 was released today. Happy to help dev and send you $20 Paypal to get lunch if that provides a little more encouragement. Great add-on that I don't want to live without :-)

**Comment by oinkin** [comment]
>Is this simply a case of the addon not declaring itself compatible with PM > 28.x

Unfortunately not. Something under the covers has changed with how PM 29 renders new tabs and we're not able to locate the UI elements as they're created. 

I thought I had more time to debug before PM 29 came out.

**Comment by oinkin** [comment]
>Happy to help dev and send you $20 Paypal to get lunch if that provides a little more encouragement. 

Please send it to your local food bank.

**Comment by Majormom167** [comment]
Yes, please do find a fix.  I agree tree tabs are the only way to go. Is there a way to uninstall the update and go back 28.xx until this is resolved?

**Comment by Vershner** [comment]
Just letting you know your work is most appreciated. Hopefully it's not too difficult to get working on v29.

**Comment by oinkin** [comment]
Thank you all for your patience and I apologize for the disruption.

**Comment by dawidi** [comment]
Excellent, thank you! :-D

**Comment by markd89** [comment]
FYI, another PM user who was not aware of oinkin's work made a build which he says works on PM29. I suggested to him to work with you. Here's the thread. https://forum.palemoon.org/viewtopic.php?f=37&t=26118&p=208168#p207914 

If nothing else, maybe his changes will help you find what's needed for a durable fix.

**Comment by oinkin** [comment]
A fixed version has already been released.

**Comment by markd89** [comment]
Much thanks!!

**Comment by Majormom167** [comment]
Hug your neck, we're back to normalcy!!!!
