### ISSUE TITLE
Issues with fullscreen in Pale Moon 28

### ISSUE THREAD

**Issue by EbonJaeger** [oinkin/treestyletab#9]
In Pale Moon 28, the event model for going to/from fullscreen changed. This causes issues with the auto-hiding of the tab bar; the bar is not hidden after entering fullscreen, and then it is hidden when exiting fullscreen.

On the Pale Moon forums I was linked to this PR which may be of some use: https://github.com/MoonchildProductions/UXP/pull/313

**Comment by Gnat008** [comment]
See these issues from the main TST repo: https://github.com/piroor/treestyletab/issues/903 and https://github.com/piroor/treestyletab/issues/910
And these PR's to fix it: https://github.com/piroor/treestyletab/pull/917 and https://github.com/piroor/treestyletab/pull/925

**Comment by JustOff** [comment]
I'm afraid this repo is abandoned, since even trivial fixes prepared as PRs are ignored since Mar 2017. I think someone interested in TST for Pale Moon needs to make another fork.

**Comment by Gnat008** [comment]
@JustOff Yeah, that's what I was afraid of.
